/*
 *  linux/include/asm-arm/arch-magus/hardware.h
 *
 *  Copyright (C) 2006 sasin@solomon-systech.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
#ifndef __ASM_ARCH_HARDWARE_H
#define __ASM_ARCH_HARDWARE_H


/* macro to get at IO space when running virtually */
#ifdef CONFIG_ARCH_MAGUS_FPGA

#define MAGUS_IO		0xD0000000
#define MAGUS_IO_NFC	0xDC000000
#define MAGUS_IO_DSP	0xE8000000
#define MAGUS_IO_CS0	0xD8000000		/* 64MB total */
#define MAGUS_IO_CS1	0xD8200000
#define MAGUS_IO_CS2	0xD8400000
#define MAGUS_IO_CS3	0xD8800000
#define MAGUS_IO_CS4	0xD8C00000
#define MAGUS_IO_CS5	0xD8E00000

#define MAGUS_CLK_AHB	40000000
#define MAGUS_CLK_APB	40000000
#define MAGUS_CLK_PER1	40000000
#define MAGUS_CLK_PER2	40000000
#define MAGUS_CLK_SDHC	MAGUS_CLK_AHB

#else

#define MAGUS_IO		0x08000000
#define MAGUS_IO_NFC	0x40000000
#define MAGUS_IO_DSP	0xD0000000
#define MAGUS_IO_CS0	0x10000000		/* 256MB */
#define MAGUS_IO_CS1	0x20000000		/* 64MB */
#define MAGUS_IO_CS2	0x24000000		/* 64MB */
#define MAGUS_IO_CS3	0x28000000		/* 32MB */
#define MAGUS_IO_CS4	0x2C000000		/* 32MB */
#define MAGUS_IO_CS5	0x2E000000		/* 32MB */

/* default clocks for Linux */
#define MAGUS_CLK_AHB	120000000
#define MAGUS_CLK_APB	60000000
#define MAGUS_CLK_PER1	60000000
#define MAGUS_CLK_PER2	60000000
#define MAGUS_CLK_SDHC	(MAGUS_CLK_AHB >> 1)	/* div2 in SDHC */

#endif

#define MAGUS_IO_SRAM	0xFFFF0000		/* 64KB */

/* APB register map */
#define MAGUS_IO_SDRAMC	(MAGUS_IO | 0x0000)
#define MAGUS_IO_EXPIO	(MAGUS_IO | 0x1000)
#define MAGUS_IO_EBM	(MAGUS_IO | 0x2000)
#define MAGUS_IO_DMAC	(MAGUS_IO | 0x3000)
#define MAGUS_IO_D2D	(MAGUS_IO | 0x4000)
#define MAGUS_IO_LCDC	(MAGUS_IO | 0x5000)
#define MAGUS_IO_DV		(MAGUS_IO | 0x6000)
#define MAGUS_IO_VIP	(MAGUS_IO | 0x7000)
#define MAGUS_IO_VPP	(MAGUS_IO | 0x8000)
#define MAGUS_IO_TVOUT	(MAGUS_IO | 0x9000)
#define MAGUS_IO_TVENC	(MAGUS_IO | 0xA000)
#define MAGUS_IO_PRISM	(MAGUS_IO | 0xB000)
#define MAGUS_IO_SCRM	(MAGUS_IO | 0x100000)
#define MAGUS_IO_INTC	(MAGUS_IO | 0x101000)
#define MAGUS_IO_I2C	(MAGUS_IO | 0x102000)
#define MAGUS_IO_UART	(MAGUS_IO | 0x103000)
#define MAGUS_IO_UART2	(MAGUS_IO | 0x104000)
#define MAGUS_IO_UART3	(MAGUS_IO | 0x105000)
#define MAGUS_IO_UART4	(MAGUS_IO | 0x106000)
#define MAGUS_IO_SPI	(MAGUS_IO | 0x107000)
#define MAGUS_IO_SPI2	(MAGUS_IO | 0x108000)
#define MAGUS_IO_TMR	(MAGUS_IO | 0x109000)
#define MAGUS_IO_TMR2	(MAGUS_IO | 0x10A000)
#define MAGUS_IO_RTC	(MAGUS_IO | 0x10B000)
#define MAGUS_IO_WDOG	(MAGUS_IO | 0x10C000)
#define MAGUS_IO_PWM	(MAGUS_IO | 0x10D000)
#define MAGUS_IO_PWM2	(MAGUS_IO | 0x10E000)
#define MAGUS_IO_GPIO	(MAGUS_IO | 0x10F000)
#define MAGUS_IO_KPP	(MAGUS_IO | 0x110000)
/* AHB register map */
#define MAGUS_IO_SDHC	(MAGUS_IO | 0x200000)
#define MAGUS_IO_SDHC2	(MAGUS_IO | 0x300000)
#define MAGUS_IO_USBD	(MAGUS_IO | 0x400000)
#define MAGUS_IO_EHCI	(MAGUS_IO | 0x403000)
#define MAGUS_IO_OTG	(MAGUS_IO | 0x404000)

/* IRQ */
#define MAGUS_IRQ_DSP	0
#define MAGUS_IRQ_LCDC	1
#define MAGUS_IRQ_TVOUT	2
#define MAGUS_IRQ_MIPI	3
#define MAGUS_IRQ_VPP	4
#define MAGUS_IRQ_VIP	5
#define MAGUS_IRQ_EBM	6
#define MAGUS_IRQ_D2D	7
#define MAGUS_IRQ_USBD	8
#define MAGUS_IRQ_DMAC	9
#define MAGUS_IRQ_SDHC	11
#define MAGUS_IRQ_SDHC2	12
#define MAGUS_IRQ_NFC	13
#define MAGUS_IRQ_EHCI	14
#define MAGUS_IRQ_OTG	15
#define MAGUS_IRQ_UART	16
#define MAGUS_IRQ_UART2	17
#define MAGUS_IRQ_UART3	18
#define MAGUS_IRQ_UART4	19
#define MAGUS_IRQ_SPI	20
#define MAGUS_IRQ_SPI2	21
#define MAGUS_IRQ_TMR	24
#define MAGUS_IRQ_TMR2	25
#define MAGUS_IRQ_I2C	26
#define MAGUS_IRQ_WDOG	27
#define MAGUS_IRQ_RTC	28
#define MAGUS_IRQ_GPIO	29
#define MAGUS_IRQ_KPP	30

/* DMA request channels */
#define MAGUS_DMA_UART_TX	0
#define MAGUS_DMA_UART_RX	1
#define MAGUS_DMA_UART2_TX	2
#define MAGUS_DMA_UART2_RX	3
#define MAGUS_DMA_UART3_TX	4
#define MAGUS_DMA_UART3_RX	5
#define MAGUS_DMA_UART4_TX	6
#define MAGUS_DMA_UART4_RX	7
#define MAGUS_DMA_SPI_TX	8
#define MAGUS_DMA_SPI_RX	9
#define MAGUS_DMA_SPI2_TX	10
#define MAGUS_DMA_SPI2_RX	11

/* peripheral clocks for baud */
#define MAGUS_CLK_I2C	MAGUS_CLK_APB
#define MAGUS_CLK_UART	MAGUS_CLK_PER1
#define MAGUS_CLK_GPIO	MAGUS_CLK_PER1
#define MAGUS_CLK_SPI	MAGUS_CLK_PER1
#define MAGUS_CLK_TVOUT	MAGUS_CLK_PER2
#define MAGUS_CLK_LCDC	MAGUS_CLK_AHB

/* virtual io map at start up */
#define MAGUS_VIO_SCRM		0xF0000000
#define MAGUS_VIO_INTC		0xF0001000
#define MAGUS_VIO_UART		0xF0003000
#define MAGUS_VIO_UART2		0xF0004000
#define MAGUS_VIO_UART3		0xF0005000
#define MAGUS_VIO_UART4		0xF0006000
#define MAGUS_VIO_TMR		0xF0009000
#define MAGUS_VIO_PWM		0xF000D000
#define MAGUS_VIO_PWM2		0xF000E000
#define MAGUS_VIO_GPIO		0xF000F000
#define MAGUS_VIO_SDRAMC  	0xF0010000
#define MAGUS_VIO_SRAM     	0xF00F0000 //64KB



#define INTC_IRQS				32
#define GPIO_PORTS				6
#define GPIO_PINS				5		/* log(pins_per_port) / log(2) */
#define GPIO_IRQS				(GPIO_PORTS << GPIO_PINS)
#define GPIO_IRQ(port, pin)		(INTC_IRQS + ((port) << 5) + (pin))
#define GPIO_IRQ_PORT(irq)		(((irq) - INTC_IRQS) >> 5)
#define GPIO_IRQ_PIN(irq)		(((irq) - INTC_IRQS) & ((1 << 5) - 1))
#define GPIO_PORT_VADDR(port)	((void *)(MAGUS_VIO_GPIO + ((port) << 8)))


/* board peripherals & gpio usage */
#ifdef CONFIG_ARCH_MAGUS_ADS
#define MAGUS_VIO_CS8900	0xFC000000
#define MAGUS_IRQ_CS8900	gpio_to_irq(GPIO_NUM(5, 22))
#define MAGUS_GPIO_TMRLED	GPIO_NUM(5, 13)
#define MAGUS_GPIO_ADS7846	GPIO_NUM(4, 4)
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#elif defined CONFIG_ACCIO_PF101
#define MAGUS_GPIO_AK4182	GPIO_NUM(3, 12)
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#define MAGUS_GPIO_VOL_UP	GPIO_NUM(0, 10)
#define MAGUS_GPIO_VOL_DOWN	GPIO_NUM(0, 11)
#elif defined CONFIG_ACCIO_PF102
#define MAGUS_GPIO_ADS7846	GPIO_NUM(2, 16)
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#elif defined CONFIG_ACCIO_CM5208
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#define MAGUS_GPIO_HOLD		GPIO_NUM(3, 10)
#elif defined CONFIG_ACCIO_CM5210
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#define MAGUS_GPIO_HOLD		GPIO_NUM(3, 10)
#elif defined CONFIG_ACCIO_A2818T
#define MAGUS_GPIO_ADS7846	GPIO_NUM(5, 22)
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#define MAGUS_GPIO_HOLD		GPIO_NUM(3, 10)
#elif defined CONFIG_ACCIO_P1
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#define MAGUS_GPIO_AK4182	GPIO_NUM(3, 12)
#define MAGUS_GPIO_VOL_UP	GPIO_NUM(4, 23)
#define MAGUS_GPIO_VOL_DOWN	GPIO_NUM(4, 21)
#elif defined CONFIG_ACCIO_LITE
#define MAGUS_GPIO_EHCIOCD  GPIO_NUM(3, 27)
#define MAGUS_GPIO_AK4182   GPIO_NUM(3, 12)
#elif defined CONFIG_LUMOS_WE8623_P0
#define MAGUS_GPIO_EHCIOCD	GPIO_NUM(3, 27)
#define MAGUS_GPIO_AK4182	GPIO_NUM(3, 12)
#define MAGUS_GPIO_VOL_UP	GPIO_NUM(4, 23)
#define MAGUS_GPIO_VOL_DOWN	GPIO_NUM(4, 21)
#endif

#define IO_ADDRESS(x) (((x) & 0xFFFFF) | 0xF0000000)


/* Magus pin & mask definitions for GPIO multiplexed pins */
#define GPIO_PORT_MAX	6

/* five bits(0~4) for 0~31 pins per port */
#define GPIO_PIN_MASK	0x1f

/* 3 bits (5~7) for max 6 ports */
#define GPIO_PORT_MASK	(0x7 << 5)

#define GPIO_PORT_SHIFT	5

/* 6 ports A ~ F */
#define GPIO_PORTA	(0<<5)
#define GPIO_PORTB	(1<<5)
#define GPIO_PORTC	(2<<5)
#define GPIO_PORTD	(3<<5)
#define GPIO_PORTE	(4<<5)
#define GPIO_PORTF	(5<<5)

/* data direction when in gpio mode - 8th bit */
#define GPIO_DIR_OUT	(1<<8)
#define GPIO_DIR_IN	(0<<8)

/* pullup enable bit - 9th bit */
#define GPIO_PUEN	(1<<9)

/* pin functions when in peripheral mode - 10th bit */
#define GPIO_PF		(0<<10) /* primary funtion */
#define GPIO_AF		(1<<10) /* alternate function */

/* for output sources - 11 & 12th bits*/
#define GPIO_OCR_SHIFT	11
#define GPIO_OCR_MASK	(3<<11)
#define GPIO_AIN	(0<<11)
#define GPIO_BIN	(1<<11)
#define GPIO_CIN	(2<<11)
#define GPIO_DR		(3<<11) /* data register */

/* for input sources - AOUT - 13 & 14th bits */
#define GPIO_AOUT_SHIFT		13
#define GPIO_AOUT_MASK		(3<<13)
#define GPIO_AOUT		(0<<13) /* GIN */
#define GPIO_AOUT_ISR		(1<<13) /* interrupt status register */
#define GPIO_AOUT_0		(2<<13)
#define GPIO_AOUT_1		(3<<13)

/* for input sources - BOUT - 15 & 16th bits*/
#define GPIO_BOUT_SHIFT		15
#define GPIO_BOUT_MASK		(3<<15)
#define GPIO_BOUT		(0<<15) /* GIN */
#define GPIO_BOUT_ISR  		(1<<15)
#define GPIO_BOUT_0    		(2<<15)
#define GPIO_BOUT_1    		(3<<15)

/* pin modes - GPIO or peripheral - 17th bit*/
#define GPIO_MODE      (1<<17)
#define PERI_MODE      (0<<17)


/* Magus Pin Definitions */

/* Port A */
#define PA24_LCDC_BYP_CS0		( GPIO_PORTA | PERI_MODE | GPIO_PF	| 24 )


#define PA22_DV_D7			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 22 )
#define PA22_TVO_D7			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 22 )
#define PA22_CX_SEM_HINT_R_2		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 22 )
#define PA22_TS_D7			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 22 )

#define PA21_DV_D6			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 21 )
#define PA21_TVO_D6			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 21 )
#define PA21_CX_SEM_HINT_R_1		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 21 )
#define PA21_TS_D6			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 21 )


#define PA20_DV_D5			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 20 )
#define PA20_TVO_D5			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 20 )
#define PA20_CX_SEM_HINT_R_0		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 20 )
#define PA20_TS_D5			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 20 )

#define PA19_DV_D4			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 19 )
#define PA19_TVO_D4			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 19 )
#define PA19_CX_CR_HINT_R		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 19 )
#define PA19_TS_D4			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 19 )

#define PA18_DV_D3			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 18 )
#define PA18_TVO_D3			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 18 )
#define PA18_CEVAXS1200_HWDATA_3	( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 18 )
#define PA18_TS_D3			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 18 )

#define PA17_DV_D2			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 17 )
#define PA17_TVO_D2			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 17 )
#define PA17_CEVAXS1200_HWDATA_2	( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 17 )
#define PA17_TS_D2			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 17 )


#define PA16_DV_D1			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 16 )
#define PA16_TVO_D1			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 16 )
#define PA16_CEVAXS1200_HWDATA_1	( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 16 )
#define PA16_TS_D1			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 16 )


#define PA15_DV_D0			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 15 )
#define PA15_TVO_D0			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 15 )
#define PA15_CEVAXS1200_HWDATA_0	( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 15 )
#define PA15_TS_D0			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 15 )


#define PA12_DV_PCLK			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 12 )
#define PA12_CEVAXS1200_HADDR_3		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 12 )
#define PA12_TS_PCLK			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 12 )


#define PA11_TVO_D15			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 11 )
#define PA11_CEVAXS1200_HADDR_2		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 11 )
#define PA11_DV_D15			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 11 )
#define PA11_TS_D7			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 11 )


#define PA10_TVO_D14			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 10 )
#define PA10_CEVAXS1200_HADDR_1		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 10 )
#define PA10_DV_D14			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 10 )
#define PA10_TS_D6			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 10 )


#define PA9_TVO_D13			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 9 )
#define PA9_CEVAXS1200_HADDR_0		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 9 )
#define PA9_DV_D13			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 9 )
#define PA9_TS_D5			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 9 )


#define PA8_TVO_D12		 	( GPIO_PORTA | PERI_MODE | GPIO_PF	| 8 )
#define PA8_CEVAXS1200_HTRANS_1		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 8 )
#define PA8_DV_D12			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 8 )
#define PA8_TS_D4			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 8 )

#define PA7_TVO_D11		 	( GPIO_PORTA | PERI_MODE | GPIO_PF	| 7 )
#define PA7_CEVAXS1200_HTRANS_0		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 7 )
#define PA7_DV_D11			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 7 )
#define PA7_TS_D3			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 7 )

#define PA6_TVO_D10		 	( GPIO_PORTA | PERI_MODE | GPIO_PF	| 6 )
#define PA6_CEVAXS1200_HWRITE		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 6 )
#define PA6_DV_D10			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 6 )
#define PA6_TS_D2			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 6 )

#define PA5_TVO_D9		 	( GPIO_PORTA | PERI_MODE | GPIO_PF	| 5 )
#define PA5_CEVAXS1200_HSIZE_2		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 5 )
#define PA5_DV_D9 			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 5 )
#define PA5_TS_D1			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 5 )

#define PA4_TVO_D8		 	( GPIO_PORTA | PERI_MODE | GPIO_PF	| 4 )
#define PA4_CEVAXS1200_HSIZE_1		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 4 )
#define PA4_DV_D8 			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 4 )
#define PA4_TS_D0			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 4 )

#define PA3_TVO_HSYNC			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 3 )
#define PA3_CEVAXS1200_HSIZE_0		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 3 )
#define PA3_TS_PSYNC			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 3 )

#define PA2_TVO_VSYNC			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 2 )
#define PA2_TVO_FIELD			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 2 )
#define PA2_CEVAXS1200_HBURST_2		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 2 )
#define PA2_TS_DVALID			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 2 )

#define PA1_TVO_PCLK			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 1 )
#define PA1_CEVAXS1200_HBURST_1		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 1 )
#define PA1_TS_PCLK			( GPIO_PORTA | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT | GPIO_PUEN | 1 )

#define PA0_TVO_MCLK			( GPIO_PORTA | PERI_MODE | GPIO_PF	| 0 )
#define PA0_DV_MCLK			( GPIO_PORTA | PERI_MODE | GPIO_AF	| 0 )
#define PA0_CEVAXS1200_HBURST_0		( GPIO_PORTA | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 0 )

/* Port B */
#define PB31_LCDCM_LD23			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 31 )
#define PB31_KP_ROW5			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 31 )
#define PB31_SDRAMC_HRDATA_3		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 31 )
#define PB31_CEVAXS1200_HRDATA_3	( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 31 )

#define PB30_LCDCM_LD22			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 30 )
#define PB30_KP_ROW4			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 30 )
#define PB30_SDRAMC_HRDATA_2		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 30 )
#define PB30_CEVAXS1200_HRDATA_2	( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 30 )

#define PB29_LCDCM_LD21			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 29 )
#define PB29_SDRAMC_HRDATA_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 29 )
#define PB29_CEVAXS1200_HRDATA_1	( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 29 )

#define PB28_LCDCM_LD20			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 28 )
#define PB28_SDRAMC_HRDATA_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 28 )
#define PB28_CEVAXS1200_HRDATA_0	( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 28 )


#define PB27_LCDCM_LD19			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 27 )

#define PB26_LCDCM_LD18			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 26 )
#define PB26_SDRAMC_HRESP_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 26 )
#define PB26_CEVAXS1200_HRESP		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 26 )

#define PB25_LCDCM_LD17			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 25 )
#define PB25_SDRAMC_HREADY		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 25 )
#define PB25_CEVAXS1200_HREADY		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 25 )

#define PB24_LCDCM_LD16			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 24 )
#define PB24_HSEL_SDRAMC_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 24 )
#define PB24_WRAP_HSEL_XS1200		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 24 )

#define PB23_LCDCM_LD15			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 23 )
#define PB23_HADDR_S2_3			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 23 )
#define PB23_WRAP_HADDR_S3_3		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 23 )

#define PB22_LCDCM_LD14			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 22 )
#define PB22_HADDR_S2_2			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 22 )
#define PB22_WRAP_HADDR_S3_2		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 22 )

#define PB21_LCDCM_LD13			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 21 )
#define PB21_HADDR_S2_1			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 21 )
#define PB21_WRAP_HADDR_S3_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 21 )

#define PB20_LCDCM_LD12			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 20 )
#define PB20_HADDR_S2_0			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 20 )
#define PB20_WRAP_HADDR_S3_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 20 )

#define PB19_LCDCM_LD11			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 19 )
#define PB19_HTRANS_S2_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 19 )
#define PB19_WRAP_HTRANS_S3_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 19 )

#define PB18_LCDCM_LD10			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 18 )
#define PB18_HTRANS_S2_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 18 )
#define PB18_WRAP_HTRANS_S3_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 18 )

#define PB17_LCDCM_SHUT			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 17 )
#define PB17_HWRITE_S2			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 17 )
#define PB17_WRAP_HWRITE_S3		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 17 )

#define PB16_LCDCM_LD9			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 16 )
#define PB16_HWDATA_S2_3		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 16 )
#define PB16_WRAP_HWDATA_S3_3		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 16 )

#define PB15_LCDCM_LD8			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 15 )
#define PB15_HWDATA_S2_2		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 15 )
#define PB15_WRAP_HWDATA_S3_2		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 15 )

#define PB14_LCDCM_LD7			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 14 )
#define PB14_HWDATA_S2_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 14 )
#define PB14_WRAP_HWDATA_S3_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 14 )

#define PB13_LCDCM_LD6			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 13 )
#define PB13_HWDATA_S2_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 13 )
#define PB13_WRAP_HWDATA_S3_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 13 )

#define PB12_LCDCM_LD5			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 12 )
#define PB12_HBURST_S2_2		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 12 )
#define PB12_WRAP_HBURST_S3_2		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 12 )

#define PB11_LCDCM_LD4			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 11 )
#define PB11_HBURST_S2_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 11 )
#define PB11_WRAP_HBURST_S3_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 11 )

#define PB10_LCDCM_LD3			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 10 )
#define PB10_HBURST_S2_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 10 )
#define PB10_WRAP_HBURST_S3_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 10 )

#define PB9_LCDCM_LD2			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 9 )
#define PB9_LCDCM_SCK			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 9 )
#define PB9_HSIZE_S2_1			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 9 )
#define PB9_WRAP_HSIZE_S3_1		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 9 )

#define PB8_LCDCM_LD1			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 8 )
#define PB8_LCDCM_SDC			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 8 )
#define PB8_HSIZE_S2_0			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 8 )
#define PB8_WRAP_HSIZE_S3_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 8 )

#define PB7_LCDCM_LD0			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 7 )
#define PB7_LCDCM_SDA			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 7 )
#define PB7_HSEL_SDRAMC_0		( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 7 )

#define PB6_LCDCM_DOTCLK		( GPIO_PORTB | PERI_MODE | GPIO_PF	| 6 )
#define PB6_LCDCM_SCK			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 6 )
#define PB6_LCDCM_CS1			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 6 )
#define PB6_LCDCM_WR			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 6 )
#define PB6_LCDCM_SDC			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 6 )

#define PB5_LCDCM_HSYNC			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 5 )
#define PB5_LCDCM_SDC			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 5 )
#define PB5_LCDCM_WR			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 5 )
#define PB5_LCDCM_SCK			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 5 )
#define PB5_LCDCM_SDA			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 5 )

#define PB4_LCDCM_VSYNC			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 4 )
#define PB4_LCDCM_WR			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 4 )
#define PB4_LCDCM_SDC			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 4 )
#define PB4_LCDCM_SDA			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 4 )
#define PB4_LCDCM_SCK			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 4 )

#define PB3_LCDCM_DEN			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 3 )
#define PB3_LCDCM_SDA			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 3 )
#define PB3_LCDCM_WR			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 3 )
#define PB3_LCDCM_SDC			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 3 )
#define PB3_LCDCM_SCK			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | GPIO_PUEN | 3 )

#define PB2_LCDCM_CS1			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 2 )
#define PB2_S2_HREADY			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 2 )

#define PB1_LCDCM_CS0			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 1 )

#define PB0_LCDCM_ROP0			( GPIO_PORTB | PERI_MODE | GPIO_PF	| 0 )
#define PB0_UART4_TXD			( GPIO_PORTB | PERI_MODE | GPIO_AF	| 0 )
#define PB0_DV_FIELD			( GPIO_PORTB | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 0 )


/* Port C */
#define PC30_NFC_CE0			( GPIO_PORTC | PERI_MODE | GPIO_PF | 30 )

#define PC29_NFC_WAIT			( GPIO_PORTC | PERI_MODE | GPIO_PF	| GPIO_PUEN | 29 )

#define PC28_EXPIO_NFC_WE		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 28 )
#define PC28_NFC_WE			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 28 )

#define PC27_EXPIO_NFC_OE		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 27 )
#define PC27_NFC_RE			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 27 )

#define PC26_EXPIO_WAIT			( GPIO_PORTC | PERI_MODE | GPIO_PF	| GPIO_PUEN | 26 )
#define PC26_NFC_RDY			( GPIO_PORTC | PERI_MODE | GPIO_AF	| GPIO_PUEN | 26 )

#define PC25_EXPIO_NFC_LBA		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 25 )
#define PC25_NFC_ALE			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 25 )

#define PC24_EXPIO_NFC_BCLK		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 24 )
#define PC24_NFC_CLE			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 24 )

#define PC23_EXPIO_CRE			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 23 )
#define PC23_NFC_CE0			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 23 )

#define PC22_EXPIO_BE1			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 22 )
#define PC22_EBM_BE1			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 22 )

#define PC21_EXPIO_BE0			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 21 )
#define PC21_EBM_BE0			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 21 )

#define PC20_EXPIO_CS4			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 20 )
#define PC20_UART3_TXD			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 20 )

#define PC19_EXPIO_CS3			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 19 )
#define PC19_UART3_RXD			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 19 )

#define PC18_EXPIO_CS2			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 18 )
#define PC18_NFC_CE1			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 18 )
#define PC18_SDHC2_LED			( GPIO_PORTC | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 18 )
#define PC18_SPI2_CS1			( GPIO_PORTC | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | GPIO_PUEN | 18 )

#define PC17_EXPIO_CS1			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 17 )
#define PC17_UART4_RXD			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 17 )
#define PC17_SDHC1_LED			( GPIO_PORTC | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | 17 )
#define PC17_SPI2_CS2			( GPIO_PORTC | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | 17 )

#define PC16_EXPIO_CS0			( GPIO_PORTC | PERI_MODE | GPIO_PF	| 16 )
#define PC16_EBM_CS			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 16 )

#define PC15_EXPIO_NFC_D15		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 15 )
#define PC15_UTM_D15			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 15 )

#define PC14_EXPIO_NFC_D14		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 14 )
#define PC14_UTM_D14			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 14 )

#define PC13_EXPIO_NFC_D13		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 13 )
#define PC13_UTM_D13			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 13 )

#define PC12_EXPIO_NFC_D12		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 12 )
#define PC12_UTM_D12			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 12 )

#define PC11_EXPIO_NFC_D11		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 11 )
#define PC11_UTM_D11			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 11 )

#define PC10_EXPIO_NFC_D10		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 10 )
#define PC10_UTM_D10			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 10 )

#define PC9_EXPIO_NFC_D9		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 9 )
#define PC9_UTM_D9			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 9 )

#define PC8_EXPIO_NFC_D8		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 8 )
#define PC8_UTM_D8			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 8 )

#define PC7_EXPIO_NFC_D7		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 7 )
#define PC7_UTM_D7			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 7 )

#define PC6_EXPIO_NFC_D6		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 6 )
#define PC6_UTM_D6			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 6 )

#define PC5_EXPIO_NFC_D5		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 5 )
#define PC5_UTM_D5			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 5 )

#define PC4_EXPIO_NFC_D4		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 4 )
#define PC4_UTM_D4			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 4 )

#define PC3_EXPIO_NFC_D3		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 3 )
#define PC3_UTM_D3			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 3 )

#define PC2_EXPIO_NFC_D2		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 2 )
#define PC2_UTM_D2			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 2 )

#define PC1_EXPIO_NFC_D1		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 1 )
#define PC1_UTM_D1			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 1 )

#define PC0_EXPIO_NFC_D0		( GPIO_PORTC | PERI_MODE | GPIO_PF	| 0 )
#define PC0_UTM_D0			( GPIO_PORTC | PERI_MODE | GPIO_AF	| 0 )

/* Port D */

#define PD27_USBOTG_PWRFAULT		( GPIO_PORTD | PERI_MODE | GPIO_PF	| 27 )

#define PD26_USBOTG_DRVVBUS		( GPIO_PORTD | PERI_MODE | GPIO_PF	| 26 )

#define PD25_EXPIO_A25			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 25 )
#define PD25_NFC_CE2			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 25 )
#define PD25_SDHC1_PWR			( GPIO_PORTD | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | 25 )
#define PD25_UART4_RTS			( GPIO_PORTD | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | 25 )

#define PD24_EXPIO_A24			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 24 )
#define PD24_NFC_CE3			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 24 )
#define PD24_SDHC2_PWR			( GPIO_PORTD | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | 24 )
#define PD24_UART4_CTS			( GPIO_PORTD | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | 24 )

#define PD23_EXPIO_A23			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 23 )
#define PD23_EBM_A4			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 23 )

#define PD22_EXPIO_A22			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 22 )
#define PD22_EBM_A3			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 22 )

#define PD21_EXPIO_A21			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 21 )
#define PD21_EBM_A2			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 21 )

#define PD20_EXPIO_A20			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 20 )
#define PD20_EBM_A1			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 20 )

#define PD19_EXPIO_A19			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 19 )
#define PD19_EBM_A0			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 19 )

#define PD18_EXPIO_A18			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 18 )
#define PD18_EBM_WE			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 18 )

#define PD17_EXPIO_A17			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 17 )
#define PD17_EBM_OE			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 17 )

#define PD16_EXPIO_A16			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 16 )
#define PD16_EBM_WAIT			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 16 )

#define PD15_EXPIO_A15			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 15 )
#define PD15_EBM_D15			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 15 )

#define PD14_EXPIO_A14			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 14 )
#define PD14_EBM_D14			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 14 )

#define PD13_EXPIO_A13			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 13 )
#define PD13_EBM_D13			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 13 )

#define PD12_EXPIO_A12			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 12 )
#define PD12_EBM_D12			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 12 )

#define PD11_EXPIO_A11			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 11 )
#define PD11_EBM_D11			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 11 )

#define PD10_EXPIO_A10			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 10 )
#define PD10_EBM_D10			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 10 )

#define PD9_EXPIO_A9			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 9 )
#define PD9_EBM_D9			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 9 )

#define PD8_EXPIO_A8			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 8 )
#define PD8_EBM_D8			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 8 )

#define PD7_EXPIO_A7			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 7 )
#define PD7_EBM_D7			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 7 )

#define PD6_EXPIO_A6			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 6 )
#define PD6_EBM_D6			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 6 )

#define PD5_EXPIO_A5			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 5 )
#define PD5_EBM_D5			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 5 )

#define PD4_EXPIO_A4			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 4 )
#define PD4_EBM_D4			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 4 )

#define PD3_EXPIO_A3			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 3 )
#define PD3_EBM_D3			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 3 )

#define PD2_EXPIO_A2			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 2 )
#define PD2_EBM_D2			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 2 )

#define PD1_EXPIO_A1			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 1 )
#define PD1_EBM_D1			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 1 )

#define PD0_EXPIO_A0			( GPIO_PORTD | PERI_MODE | GPIO_PF	| 0 )
#define PD0_EBM_D0			( GPIO_PORTD | PERI_MODE | GPIO_AF	| 0 )




/* Port E */
#define PE31_SDHC2_WP			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 31 )
#define PE31_KP_COL2			( GPIO_PORTE | PERI_MODE | GPIO_AF | 31 )
#define PE31_CX_RST_N			( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 31 )

#define PE30_SDHC2_CMD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 30 )
#define PE30_KP_COL1			( GPIO_PORTE | PERI_MODE | GPIO_AF | 30 )
#define PE30_CX_SYS_RST_N		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 30 )

#define PE29_SDHC2_CLK			( GPIO_PORTE | PERI_MODE | GPIO_PF	| 29 )
#define PE29_KP_COL0			( GPIO_PORTE | PERI_MODE | GPIO_AF | 29 )
#define PE29_INTC_FIRQ_B		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 29 )

#define PE28_SDHC2_DAT3			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 28 )
#define PE28_KP_ROW3			( GPIO_PORTE | PERI_MODE | GPIO_AF | 28 )
#define PE28_INTC_IRQ_B			( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 28 )

#define PE27_SDHC2_DAT2			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 27 )
#define PE27_KP_ROW2			( GPIO_PORTE | PERI_MODE | GPIO_AF | 27 )
#define PE27_SCRM_LPMODE		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 27 )

#define PE26_SDHC2_DAT1			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 26 )
#define PE26_KP_ROW1			( GPIO_PORTE | PERI_MODE | GPIO_AF | 26 )
#define PE26_SCRM_SDRAMC_PWRDN		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 26 )

#define PE25_SDHC2_DAT0			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 25 )
#define PE25_KP_ROW0			( GPIO_PORTE | PERI_MODE | GPIO_AF | 25 )
#define PE25_SCRM_SDRAMC_LPACK		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 25 )

#define PE24_SSI1_CLK			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 24 )
#define PE24_UTM_CLK30			( GPIO_PORTE | PERI_MODE | GPIO_AF | 24 )

#define PE23_SSI1_FPM			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 23 )

#define PE22_SSI1_RXDAT			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 22 )

#define PE21_SSI1_TXDAT			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 21 )
#define PE21_UTM_VALIDH			( GPIO_PORTE | PERI_MODE | GPIO_AF | 21 )

#define PE19_RST_OUT_B			( GPIO_PORTE | PERI_MODE | GPIO_PF	| 19 )
#define PE18_BATTPROT			( GPIO_PORTE | PERI_MODE | GPIO_PF	| 18 )
#define PE17_TDO			( GPIO_PORTE | PERI_MODE | GPIO_PF	| 17 )
#define PE16_TRST			( GPIO_PORTE | PERI_MODE | GPIO_PF	| 16 )

#define PE15_SDHC1_CMD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 15 )
#define PE15_UTM_XCVR			( GPIO_PORTE | PERI_MODE | GPIO_AF | 15 )

#define PE14_SDHC1_CLK			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 14 )
#define PE14_UTM_TERM			( GPIO_PORTE | PERI_MODE | GPIO_AF | 14 )

#define PE13_SDHC1_DAT3			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 13 )
#define PE13_UTM_OP0			( GPIO_PORTE | PERI_MODE | GPIO_AF | 13 )

#define PE12_SDHC1_DAT2			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 12 )
#define PE12_UTM_OP1			( GPIO_PORTE | PERI_MODE | GPIO_AF | 12 )

#define PE11_SDHC1_DAT1			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 11 )
#define PE11_UTM_SUSPEND_B		( GPIO_PORTE | PERI_MODE | GPIO_AF | 11 )

#define PE10_SDHC1_DAT0			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 10 )

#define PE9_SDHC1_CD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 9 )
#define PE9_UTM_BUS16_8			( GPIO_PORTE | PERI_MODE | GPIO_AF | 9 )

#define PE8_SDHC1_WP			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 8 )
#define PE8_UTM_VCLOAD_B		( GPIO_PORTE | PERI_MODE | GPIO_AF | 8 )

#define PE7_UART1_TXD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 7 )
#define PE7_UTM_VC3			( GPIO_PORTE | PERI_MODE | GPIO_AF | 7 )

#define PE6_UART1_RXD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 6 )
#define PE6_UTM_VC2			( GPIO_PORTE | PERI_MODE | GPIO_AF | 6 )

#define PE5_UART1_CTS			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 5 )
#define PE5_UTM_VC1			( GPIO_PORTE | PERI_MODE | GPIO_AF | 5 )

#define PE4_UART1_RTS			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 4 )
#define PE4_UTM_VC0			( GPIO_PORTE | PERI_MODE | GPIO_AF | 4 )

#define PE3_UART2_TXD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 3 )
#define PE3_UTM_RESET			( GPIO_PORTE | PERI_MODE | GPIO_AF | 3 )

#define PE2_UART2_RXD			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 2 )
#define PE2_UTM_TXVALID			( GPIO_PORTE | PERI_MODE | GPIO_AF | 2 )

#define PE1_UART2_CTS			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 1 )
#define PE1_UTM_LS1			( GPIO_PORTE | PERI_MODE | GPIO_AF | 1 )
#define PE1_CORE_CX_CVERBIT		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 1 )

#define PE0_UART2_RTS			( GPIO_PORTE | PERI_MODE | GPIO_PF	| GPIO_PUEN | 0 )
#define PE0_UTM_LS0			( GPIO_PORTE | PERI_MODE | GPIO_AF | 0 )
#define PE0_CORE_CX_PEOTBIT		( GPIO_PORTE | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 0 )

/* Port F */
#define PF30_SPI1_CS3			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 30 )
#define PF30_UTM_TXRDY			( GPIO_PORTF | PERI_MODE | GPIO_AF | 30 )

#define PF29_SPI1_CS2			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 29 )
#define PF29_UTM_RXVALID		( GPIO_PORTF | PERI_MODE | GPIO_AF | 29 )

#define PF28_SPI1_CS1			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 28 )
#define PF28_UTM_RXACTIVE		( GPIO_PORTF | PERI_MODE | GPIO_AF | 28 )

#define PF27_SPI1_CS0			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 27 )
#define PF27_UTM_RXERR			( GPIO_PORTF | PERI_MODE | GPIO_AF | 27 )
#define PF27_WDT_TOUT			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 27 )

#define PF26_SPI1_CLK			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 26 )
#define PF26_UTM_VSTA7			( GPIO_PORTF | PERI_MODE | GPIO_AF | 26 )
#define PF26_WDT_PROBE			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 26 )

#define PF25_SPI1_MOSI			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 25 )
#define PF25_UTM_VSTA6			( GPIO_PORTF | PERI_MODE | GPIO_AF | 25 )
#define PF25_RTC_PROBE			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 25 )

#define PF24_SPI1_MISO			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 24 )
#define PF24_UTM_VSTA5			( GPIO_PORTF | PERI_MODE | GPIO_AF | 24 )

#define PF23_PWM2_OUT1			( GPIO_PORTF | PERI_MODE | GPIO_PF	| 23 )
#define PF23_TMR1_TOUT			( GPIO_PORTF | PERI_MODE | GPIO_AF | 23 )
#define PF23_TMR2_TOUT			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | 23 )
#define PF23_UART4_TXD			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN | 23 )
#define PF23_LCDCM_RD			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_CIN | 23 )


#define PF22_PWM2_OUT0			( GPIO_PORTF | PERI_MODE | GPIO_PF	| 22 )
#define PF22_TMR1_TIN			( GPIO_PORTF | PERI_MODE | GPIO_AF | 22 )
#define PF22_LCDCM_RD			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | 22 )
#define PF22_TMR2_TIN			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | 22 )

#define PF21_I2S_RXCLK			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 21 )
#define PF21_UTM_VSTA4			( GPIO_PORTF | PERI_MODE | GPIO_AF | 21 )
#define PF21_TVENC_PROBE0		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 21 )

#define PF20_I2S_RXFPM			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 20 )
#define PF20_UTM_VSTA3			( GPIO_PORTF | PERI_MODE | GPIO_AF | 20 )
#define PF20_TVENC_PROBE1		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 20 )

#define PF19_I2S_RXDAT			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 19 )
#define PF19_UTM_VSTA2			( GPIO_PORTF | PERI_MODE | GPIO_AF | 19 )

#define PF18_I2S_TXCLK			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 18 )
#define PF18_UTM_VSTA1			( GPIO_PORTF | PERI_MODE | GPIO_AF | 18 )

#define PF17_I2S_TXFPM			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 17 )
#define PF17_UTM_VSTA0			( GPIO_PORTF | PERI_MODE | GPIO_AF | 17 )

#define PF16_I2S_TXDAT			( GPIO_PORTF | PERI_MODE | GPIO_PF	| GPIO_PUEN | 16 )
#define PF16_UTM_IDPULLUP		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN 	| GPIO_PUEN | 16 )

#define PF15_I2C_SDA			( GPIO_PORTF | PERI_MODE | GPIO_PF | 15 )
#define PF15_UTM_DPPULLDOWN		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN 	| GPIO_PUEN | 15 )

#define PF14_I2C_SCL			( GPIO_PORTF | PERI_MODE | GPIO_PF | 14 )
#define PF14_UTM_DMPULLDOWN		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN 	| GPIO_PUEN | 14 )

#define PF13_PWM1_OUT3			( GPIO_PORTF | PERI_MODE | GPIO_PF | 13 )
#define PF13_UART3_RTS			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 13 )
#define PF13_UTM_CHRGVBUS		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN 	| GPIO_PUEN | 13 )
#define PF13_TS_DVALID			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 13 )

#define PF12_PWM1_OUT2			( GPIO_PORTF | PERI_MODE | GPIO_PF | 12 )
#define PF12_KP_COL5			( GPIO_PORTF | PERI_MODE | GPIO_AF | 12 )
#define PF12_SJMT_CX_GLOBALRSTN		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 12 )
#define PF12_UTM_DISCHRGVBUS		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN 	| GPIO_PUEN | 12 )
#define PF12_UART3_CTS			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT 	| GPIO_PUEN | 12 )
#define PF12_TS_PSYNC			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 12 )

#define PF11_PWM1_OUT1			( GPIO_PORTF | PERI_MODE | GPIO_PF | 11 )
#define PF11_KP_COL4			( GPIO_PORTF | PERI_MODE | GPIO_AF | 11 )
#define PF11_SJMT_CX_RSTN		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 11 )
#define PF11_UTM_XCVR_1			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_BIN 	| GPIO_PUEN | 11 )

#define PF10_PWM1_OUT0			( GPIO_PORTF | PERI_MODE | GPIO_PF | 10 )
#define PF10_SJMT_CX_BOOT		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 10 )
#define PF10_UTM_HOSTDISC		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 10 )

#define PF9_OCEM_TDI			( GPIO_PORTF | PERI_MODE | GPIO_PF | 9 )
#define PF9_SPI2_CLK			( GPIO_PORTF | PERI_MODE | GPIO_AF | 9 )
#define PF9_UTM_IDDIG			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 9 )

#define PF8_OCEM_TDO			( GPIO_PORTF | PERI_MODE | GPIO_PF | 8 )
#define PF8_SPI2_CS0			( GPIO_PORTF | PERI_MODE | GPIO_AF | 8 )
#define PF8_UTM_AVALID			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 8 )

#define PF7_OCEM_TMS			( GPIO_PORTF | PERI_MODE | GPIO_PF | 7 )
#define PF7_UTM_BVALID			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 7 )

#define PF6_OCEM_TCK			( GPIO_PORTF | PERI_MODE | GPIO_PF | 6 )
#define PF6_SPI2_MOSI			( GPIO_PORTF | PERI_MODE | GPIO_AF | 6 )
#define PF6_UTM_VBUSVALID		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 6 )

#define PF5_OCEM_TRST			( GPIO_PORTF | PERI_MODE | GPIO_PF | 5 )
#define PF5_SPI2_MISO			( GPIO_PORTF | PERI_MODE | GPIO_AF | 5 )
#define PF5_UTM_SESSEND			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_BOUT 	| GPIO_PUEN | 5 )

#define PF4_SSI2_CLK			( GPIO_PORTF | PERI_MODE | GPIO_PF | 4 )
#define PF4_PWM2_OUT0			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN 	| GPIO_PUEN | 4 )

#define PF3_SSI2_FSYNC			( GPIO_PORTF | PERI_MODE | GPIO_PF | GPIO_PUEN | 3 )
#define PF3_LCDCM_ROP3			( GPIO_PORTF | PERI_MODE | GPIO_AF | 3 )
#define PF3_PWM2_OUT1			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 3 )

#define PF2_SSI2_TXDAT			( GPIO_PORTF | PERI_MODE | GPIO_PF | GPIO_PUEN | 2 )
#define PF2_LCDCM_ROP2			( GPIO_PORTF | PERI_MODE | GPIO_AF | 2 )
#define PF2_PWM2_OUT2			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 2 )
#define PF2_DV_HVALID			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 2 )

#define PF1_SSI2_RXDAT			( GPIO_PORTF | PERI_MODE | GPIO_PF | GPIO_PUEN | 1 )
#define PF1_LCDCM_ROP1			( GPIO_PORTF | PERI_MODE | GPIO_AF | 1 )
#define PF1_PWM2_OUT3			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 1 )
#define PF1_DV_VVALID			( GPIO_PORTF | GPIO_MODE | GPIO_DIR_IN | GPIO_AOUT | GPIO_PUEN | 1 )

#define PF0_SDHC2_CD			( GPIO_PORTF | PERI_MODE | GPIO_PF | GPIO_PUEN | 0 )
#define PF0_KP_COL3			( GPIO_PORTF | PERI_MODE | GPIO_AF | 0 )
#define PF0_CX_OCM_CORE_RST		( GPIO_PORTF | GPIO_MODE | GPIO_DIR_OUT | GPIO_AIN | GPIO_PUEN | 0 )


#endif

