#
# linux/drivers/rtc/ssl/Makefile
#
obj-$(CONFIG_RTC_DRV_SSL) := sslrtc.o
sslrtc-objs := ssl_rtc.o rtc.o
#EXTRA_CFLAGS += -DIO_MAP=1 -DINTC=0 -DPERIODIC_ALARM -DLINUX_VERSION=020622
EXTRA_CFLAGS += -DIO_MAP=1 -DINTC=0 -DLINUX_VERSION=020622
