# Magus Platform Support
snd-soc-magus-pcm-objs := magus-pcm.o
snd-soc-magus-wm8731-objs := wm8731.o wm8731-thread.o
snd-soc-magus-i2s-objs := magus-i2s.o
snd-soc-magus-objs := magus.o
#snd-codec-wm8987-objs := wm8987.o wm8987-thread.o wm8987-interface.o
#snd-soc-magus-wm8987-objs := magus-wm8987.o
#snd-codec-wm8978-objs := wm8978.o wm8978-thread.o wm8978-interface.o
#snd-soc-magus-wm8978-objs := magus-wm8978.o

obj-$(CONFIG_SND_SOC_MAGUS) += snd-soc-magus.o dummy_piu/
obj-$(CONFIG_SND_SOC_MAGUS_WM8731) += snd-soc-magus-wm8731.o
obj-$(CONFIG_SND_SOC_MAGUS_I2S) += snd-soc-magus-i2s.o
obj-$(CONFIG_SND_SOC_MAGUS_PCM) += snd-soc-magus-pcm.o
#obj-$(CONFIG_SND_SOC_MAGUS_WM8987) += snd-soc-magus-wm8987.o dummy_piu/
#obj-$(CONFIG_SND_CODEC_MAGUS_WM8987) += snd-codec-wm8987.o
#obj-$(CONFIG_SND_SOC_MAGUS_WM8978) += snd-soc-magus-wm8978.o dummy_piu/
#obj-$(CONFIG_SND_CODEC_MAGUS_WM8978) += snd-codec-wm8978.o
